.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ECHOPING_WHOIS 1 "May 26, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
echoping_whois \- echoping plugin which connects to a whois server
.SH SYNOPSIS
.B echoping
.RI [echoping\ options]
.RI -m\ whois
.B hostname
.RI [-d]
.RI request
.SH DESCRIPTION
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
whois is an echoping plugin to connect to whois/nicname servers (see
RFC 3912).
.SH ARGUMENTS
.TP
.B request
The request to the whois server (typically a domain name)
.SH OPTIONS
.TP
.B \-d, \-\-dump
Dumps the result of the request
.SH SEE ALSO
.BR echoping (1),
.SH AUTHOR
Stephane Bortzmeyer <bortz@users.sourceforge.net>
