.\" $Id$
.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ECHOPING_LDAP 1 "May 26, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
echoping_ldap \- echoping plugin which connects to a LDAP server
.SH SYNOPSIS
.B echoping
.RI [echoping\ options]
.RI -m\ ldap
.B hostname
.RI [-b base]
.RI [-r request]
.RI [-s scope]
.RI [-p port]
.SH DESCRIPTION
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
ldap is an echoping plugin to connect to LDAP servers.
.SH OPTIONS
.TP
.B \-r request
The request to the LDAP server, in LDAP filter language. By default (objectclass=*).
.TP
.B \-b base
Base of the search, for instance "dc=current,dc=bugs,dc=debian,dc=org"
.TP
.B \-s scope
Scope of the search, "sub", "one" or "base"
.TP
.B \-p port
TCP port to use
.SH SEE ALSO
.BR echoping (1),
.SH AUTHOR
Stephane Bortzmeyer <bortz@users.sourceforge.net>
