#!/bin/sh

# For developers only: use it only if you know about autotools. 

set -e

# Does *not* work with automake 1.4!
aclocal
autoheader
libtoolize --force
automake --add-missing 
autoconf
cd plugins
aclocal
automake --foreign --add-missing
autoconf
for dir in dns random whois ldap postgresql; do
   cd $dir
   aclocal
   autoheader
   automake --foreign --add-missing
   autoconf
   cd ..
done
cd ..
