#!/bin/sh

# $Id$

echo ""
echo "Since this tests tries remote servers, a failure is not always "
echo " echoping's fault: it may be a network problem."

./echoping -C -h / www.gandi.net

./echoping -C -h / www.modssl.org

./echoping -C -h / www.creditmutuel.fr


