#!/bin/sh

# $Id$

echo ""
echo "Since this tests tries remote servers, a failure is not always "
echo " echoping's fault: it may be a network problem."

./echoping central.internatif.org

./echoping -h / www.debian.org

./echoping -h / www.freenix.org

./echoping -S mail.hotmail.com
