#!/bin/sh

# $Id$

echo ""
echo "Since this tests tries remote servers, a failure is not always "
echo " echoping's fault: it may be a network problem."

./echoping -C -h / www.gandi.net

echo ""

# We need to iterate to catch some SSL programming errors. See bug #130151 
#./echoping -C -h / -n 2 www.modssl.org
./echoping -C -h / -n 2 www.verisign.com

echo ""

# bug #230384 
./echoping -C -h / -n 2 www.ssl.de


