#!/bin/sh

# $Id$

echo ""
echo "A message such as 'connection refused' is not always an error"
echo " you may not have an appropriate server."
echo " UDP tests can also fail with a timeout if you do not have the server."

# Funny Solaris: "localhost" resolves to an IPv6 address (::1)

./echoping localhost
./echoping -u localhost
./echoping -d localhost
./echoping -d -u localhost
#./echoping -c localhost # chargen is too often unavailable
./echoping -h / localhost
