#!/bin/sh

# $Id$

echo ""
echo "Since this tests tries remote servers, a failure is not always "
echo " echoping's fault: it may be a network problem."
echo ""
echo "For this specific test, you *must* set the locale to UTF-8. It is system-"
echo "dependent but you typically 'export LC_CTYPE=xx_XX.utf8'. 'locale -a' to get"
echo "possible values."

./echoping -h / -v café.gennic.net

