#!/bin/sh

# $Id$

echo ""
echo "Since this tests tries remote servers, a failure is not always "
echo " echoping's fault: it may be a network problem."

./echoping -6 -h / -v www.ripe.net

./echoping -6 -h / -v www.afnic.fr

./echoping -6 -v -R -h / "[2001:4f8:0:2::d]:80" # RFC 3986, section 3.2.2

# We force the use of IPv6 with -6 because some libc (Solaris) are
# smart enough to send only the IPv4 adresses to the application if
# the machine has no IPv6 connectivity.

