#!/bin/sh

# $Id$

echo ""
echo "Since this tests tries remote servers, a failure is not always "
echo " echoping's fault: it may be a network problem."
echo ""

for plugin in `ls plugins`; do
	if [ -d plugins/$plugin ]; then
	    cd plugins/$plugin
	    if [ -x ./test.sh ]; then
		echo "Testing $plugin..."
		sh ./test.sh
		echo ""
	    fi
	    cd ../..
	fi
done
