#!/bin/sh

# $Id$

echo ""
echo "Since this tests tries remote servers, a failure is not always "
echo " echoping's fault: it may be a network problem."
echo "On some systems, you may NEED to be root."

# Raise the precedence to "critic" (RFC 791, section 3.1)
./echoping -P 0xa0 -h / www.gullitv.fr

# IPTOS_THROUGHPUT  
./echoping -P 0x08 -h / www.gullitv.fr



